apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: elaidrahma/studentmanager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/springdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root123"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SERVER_PORT
          value: "8089"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/student"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.MySQL8Dialect"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MySQL8Dialect"
        # Readiness probe pour attendre MySQL
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z mysql-service 3306"
          initialDelaySeconds: 10
          periodSeconds: 5
        # Optionnel : restart policy
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
